### ISSUE TITLE
TAC Map

### ISSUE THREAD

**Issue by Joannou1** [Joannou1/GLServers#1]
Seriously, I've been saying we need to get this back for the past 2 years.

Old Plan:
Network Drive.
Network drive is not very possible, it's an expensive option, slow, and will ultimately lag the server due to rendering.

New Plan:
Find a map renderer that will render at a much lower resolution and only use half the cores.
This will reduce server load and disk usage greatly.

Dynmap does have a resolution/detial/max cores option, must look into this more.

**Comment by Kladdkaka** [comment]
Could be worth take a look at the settings for the dynmap plugin we used to have. https://github.com/webbukkit/dynmap/wiki/HD-Map-Configuration seems like you can lower the filesize by changing from png to jpg etc.

**Comment by Joannou1** [comment]
It's finally done!
Yay.

http://maps.gld.bz/

Works great, put it all over the site and on the auto announcer.
