### ISSUE TITLE
Towny assistants/vip

### ISSUE THREAD

**Issue by Kladdkaka** [Joannou1/GLServers#11]
Add more perms for assistants, make so assistants can build in other plots, claim chunks etc. Make towny vip work.

**Comment by Joannou1** [comment]
Assistant:
towny.claimed.owntown.\* (Modify anything in their town)
towny.command.town.set.board (Set board message)
towny.command.town.set.plotprice (Manage plot sale prices, I think)
towny.command.town.set.tag (Manage tags)
towny.command.town.add (Invite people to the town)

They already have towny.command.plot.*, so they should be able to claim, sell, etc.

VIP:
towny.tax_exempt (Self explanatory)
towny.command.town.add (Invite people to the town)

Whaddya think?

**Comment by Kladdkaka** [comment]
Sounds great, I would add towny.command.town.claim.town to assistant though.

**Comment by Joannou1** [comment]
Alright done, anything else for VIP.. Or should this issue be closed?

**Comment by Kladdkaka** [comment]
I think think it's good, we can close it :smile:

**Comment by Joannou1** [comment]
Alright, knocked another one down. Yay :P
