### ISSUE TITLE
Add No Cheat Plus - Plugin Suggestions

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#12]
I know NoCheat is buggy when it tries to stop a player from hacking but it would help the staff a lot of we just got notifications on when a player may be hacking. This way no player is sling shotted back to another location but rather staff get notified that there may be a hacker and that we should look into that specific player.

**Comment by Joannou1** [comment]
I will look into adding it for just monitoring purposes. Hopefully they improved the plugin performance.

**Comment by fpkaliii** [comment]
Why not add Anticheat instead? 
http://dev.bukkit.org/bukkit-plugins/anticheat/

**Comment by TyJcksn** [comment]
@cdriza Does it have the ability to notify staff members while not impairing players? I may have missed that bit.

**Comment by fpkaliii** [comment]
@TJ1632 Yes!

**Comment by Joannou1** [comment]
Complete!
Seems to work well, immediately caught an auto clicker.
Minimal false positives.

Added NCP to all servers, configured configs + perms.

Sorry @cdriza but NCP and GLD have a history, I had to give it another chance :P

**Comment by fpkaliii** [comment]
@Joannou1 Its fine, AntiCheat was discontinued as TnTBass left anyway :/
