### ISSUE TITLE
Discuss clearing the ban list

### ISSUE THREAD

**Issue by Joannou1** [Joannou1/GLServers#15]
So, we have banned 6000+ players from the GLD.

We've been talking about clearing the list, give it another go.

Discuss?

**Comment by Kladdkaka** [comment]
Sounds great, but we should reban people who obviously should be banned (RetroMonkey etc)

**Comment by TyJcksn** [comment]
I agree, a universal unban would be cool but we would need to make sure we rebanned all the unwanteds, also having nocheatnotifications would help us catch any of the hackers that would still be hacking.
<img src="http://i.imgur.com/oZwSwJ2.png">

**Comment by Joannou1** [comment]
Yeah, I got a small list of uber-permabanned players:
(names may not be entirely accurate)

splaph retromonkey nathanleese hobohunter thatflywhiteguy mcfluffykins ziggy2988 purplejuiceman blackneko battleshroud Wthrwthr

**Comment by Kladdkaka** [comment]
I can get a list of accurate names when I get home, we should maybe add sparkey914 & cdriza to the list, and remove ziggy as I believe hes unbanned.

**Comment by Joannou1** [comment]
Alright, yeah... those two gotta be added in as well.

**Comment by Kladdkaka** [comment]
great :smile:

**Comment by Joannou1** [comment]
All done. Everything integrated.

**Comment by fpkaliii** [comment]
@xenu99 "I can get a list of accurate names when I get home, we should maybe add sparkey914 & cdriza to the list, and remove ziggy as I believe hes unbanned."

Damnuxenu

**Comment by fpkaliii** [comment]
and who is mcfluffykins?

**Comment by fpkaliii** [comment]
I think you should remove #cdriza from the banlist :)
