### ISSUE TITLE
Add MobCash to Servers

### ISSUE THREAD

**Issue by Joannou1** [Joannou1/GLServers#18]
Very addictive gameplay element.
Adds a good dynamic and meaning to slaughtering innocent creatures.

**Comment by TyJcksn** [comment]
Is this where you get a payment for killing mobs?

**Comment by Joannou1** [comment]
Yeah, you can set how much you get per mob type.

**Comment by Kladdkaka** [comment]
In my opinion, we should find or modify a mobcash plugin to only give money when you kill mobs that isn't spawned from a spawner, like how mcmmo gives exp only when you kill natural spawned mobs, unless it's changed in the config.

**Comment by Joannou1** [comment]
that's what I was thinking, else people would just grind like crazy and ruin the economy... 
So I gotta search for one that does naturally spawned mobs.

**Comment by Kladdkaka** [comment]
awesome :)!

**Comment by Kladdkaka** [comment]
http://dev.bukkit.org/bukkit-plugins/killermoney/ that does natural mobs only, tried it and it works :)

**Comment by TyJcksn** [comment]
I'm just afraid that would kill the economy, even with it set to natural spawning.

**Comment by Joannou1** [comment]
Not sure about that, wild mobs are wild.. Just have to set the price right.

**Comment by TyJcksn** [comment]
Seems like mined natural spawners keep their natural aspect. May want to rethink this

**Comment by TyJcksn** [comment]
Op economy is back, no longer needed.
