### ISSUE TITLE
Update GLPixelmon Website

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#19]
Update the Pixelmon website, Jerome said he may be able to do it but he doesn't know what you would want.

**Comment by Joannou1** [comment]
All done (I think!)
Leme know what you think (you can still comment on a closed issue)

http://p.gld.bz/

**Comment by Kladdkaka** [comment]
I like it :smile:

**Comment by TyJcksn** [comment]
Looks great! Is it possible to get tac map live on that once again?
