### ISSUE TITLE
Purchase "NoProxy"

### ISSUE THREAD

**Issue by Joannou1** [Joannou1/GLServers#24]
It's only $2...
Blocks tons and tons of proxies, VPN's etc...
I'm looking at you, cdriza.

http://www.spigotmc.org/resources/noproxy.979/

**Comment by InMyToboggan** [comment]
I think that looks ok, and it's pretty cheap so may as well give it a go.

**Comment by Joannou1** [comment]
Purchased, installed and configured.

Hope it works well!
