### ISSUE TITLE
Ban management plugin

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#26]
With GLD expanding into adding other servers I think a universal ban management plugin would help a lot! This plugin keeps tracks of who was banned, when, what server, and why; all of that and more. With the idea of purging the ban list floating around this would be perfect to add for when it does happen.
http://dev.bukkit.org/bukkit-plugins/ban-management/

**Comment by fpkaliii** [comment]
Even more ways to ban me! Yay! 

Good idea though @TJ1632

**Comment by Joannou1** [comment]
All done. Everything integrated.
