### ISSUE TITLE
UHC

### ISSUE THREAD

**Issue by Kladdkaka** [Joannou1/GLServers#30]
UHC servers seems to be the new big thing, we should consider making our own, heres a plugin that looks great. http://dev.bukkit.org/bukkit-plugins/uhc/

**Comment by Kladdkaka** [comment]
Bump

**Comment by Joannou1** [comment]
Seems really cool, may want to add it after we get the current project sorted out and the playerbase steadies :)

**Comment by TyJcksn** [comment]
Moved it to a better idea
