### ISSUE TITLE
Edit Side Stats Text/Stuff

### ISSUE THREAD

**Issue by Joannou1** [Joannou1/GLServers#33]
[7:17:48 AM] TŸ Jåčkšōn - TJ1632: http://i.imgur.com/tQ5Bg8Q.png
Stats should be replaced with &7GLDesert
Money should be &eMoney
Online should be &eOnline
Maybe add a feature that tells you when you're still in combat tag
[7:18:40 AM] TŸ Jåčkšōn - TJ1632: http://i.imgur.com/EpYVfU0.png 

Seems pretty good to me, will see what I can do later.

**Comment by fpkaliii** [comment]
Seems like a good idea.

+1 :D

**Comment by Joannou1** [comment]
Added some more stuff, changed some colors:

![c305f](https://cloud.githubusercontent.com/assets/997747/4115388/50eacfb0-3277-11e4-9855-6c3959d8ceaa.png)
