### ISSUE TITLE
Re-install an actual WorldBorder plugin

### ISSUE THREAD

**Issue by Joannou1** [Joannou1/GLServers#35]
Checking the tac map, I can see some suspicious looking areas where players may be escaping the map.

The new WorldBorder works very well, we tried it on the Timewars server with a bunch of modded vehicles/mobs and it stopped us 100% of the time.

**Comment by fpkaliii** [comment]
Yay! :dancers:

**Comment by Joannou1** [comment]
Added, tested, confirmed.
Works well.
