### ISSUE TITLE
SkywarsServers.com - Update images, tags, etc

### ISSUE THREAD

**Issue by Joannou1** [Joannou1/GLServers#36]
I spent the entire day duplicating the site from pixelmonservers.co.

Rewrote the server ping script, much more intensive now, it will get the correct player amounts 95% of the time now.

So yeah... Note to self: Replace the logo images and ask Bert for tag suggestions.

Also, remove global self advertisement for now, until at least 1 page of servers are listed.

**Comment by fpkaliii** [comment]
@Joannou1 

Lolwut
http://prntscr.com/4jdpu0

**Comment by Joannou1** [comment]
Yeah.. I was gona give them a funny image and description.. but instead I just removed them :P

**Comment by Kladdkaka** [comment]
ded?
