### ISSUE TITLE
Add tools to Kit Starter

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#37]
The noobs need some form tools, the /kit starter is pretty bare at the moment

**Comment by InMyToboggan** [comment]
Yeah, maybe re-add Iron tools

**Comment by Kladdkaka** [comment]
why not make a /kit tools instead :3

**Comment by Kindofjakii** [comment]
Nah, might as well include it in kit starter, iron tools like before I say.

**Comment by Joannou1** [comment]
Ok so...
I added just the basic tools (mins the hoe) to the noob and starter kit. (Durability 1 tools to noob kit)
The noob one will follow the current convention of having an enchant on them.

(One time, first joiner kit)
![Kit NOOB](http://gld.bz/c/69203.png)

And the starter kit which can be reused every 30 minutes:
![Kit NOOB](http://gld.bz/c/cea07.png)

Think this should be enough?
I think in this day and age (at least for GLD) diamond tools should be at least standard.

**Comment by TyJcksn** [comment]
Good to go
