### ISSUE TITLE
Add BuyCraft Pics

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#40]
Adding some package pictures will help improve GLServers to seem more official. 
Each package will help represent GLServers in a specific way.

**Comment by TyJcksn** [comment]
<img src="http://i.imgur.com/HVIJITI.png">

<img src="http://i.imgur.com/Oz7qNIJ.png">

<img src="http://i.imgur.com/96lQAAg.png">

<img src="http://i.imgur.com/Ke3MoQP.png">

<img src="http://i.imgur.com/4OV2Odd.png">

<img src="http://i.imgur.com/5Oaohpm.png">

<img src="http://i.imgur.com/u9fWybe.png">

<img src="http://i.imgur.com/RvNLeKK.png">

<img src="http://i.imgur.com/4xHbYXu.png">

<img src="http://i.imgur.com/BrKZR1I.png">

<img src="http://i.imgur.com/YLJxqKJ.png">

<img src="http://i.imgur.com/l82uwaI.png">

<img src="http://i.imgur.com/mK3YfeB.png">

<img src="http://i.imgur.com/aVAr5xr.png">

<img src="http://i.imgur.com/LPoXeeZ.png">

<img src="http://i.imgur.com/BPtIPTl.png">

<img src="http://i.imgur.com/YCVu8qH.png">

<img src="http://i.imgur.com/zP6IdRv.png">

For when pets are sold in the you know what ^

**Comment by Joannou1** [comment]
Not too bad... what do you think? A bit of whitespace, but looks good.
http://gldesert.com/donate/packages/spawners/
http://gldesert.com/donate/packages/special/

The other images are a big out of place, etc.. not sure if I can work em in..

**Comment by TyJcksn** [comment]
Might aswell add lines of the same picture next to each other to fill up the white space
