### ISSUE TITLE
Fix the HTML Plugin error - LOGS

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#43]
2014/09/12 00:00:38 [ChestShop] You lack the necessary HTML files in your plugins/ChestShop/HTML folder!
2014/09/12 00:01:38 [ChestShop] You lack the necessary HTML files in your plugins/ChestShop/HTML folder!
2014/09/12 00:02:38 [ChestShop] You lack the necessary HTML files in your plugins/ChestShop/HTML folder!
2014/09/12 00:03:38 [ChestShop] You lack the necessary HTML files in your plugins/ChestShop/HTML folder!
2014/09/12 00:04:38 [ChestShop] You lack the necessary HTML files in your plugins/ChestShop/HTML folder!
2014/09/12 00:05:38 [ChestShop] You lack the necessary HTML files in your plugins/ChestShop/HTML folder!

**Comment by Joannou1** [comment]
Fixed issue in plugin at next reboot, ran a script against all the logs to remove every line that that occurs on.
