### ISSUE TITLE
Give 1337+ nocheat speed bypass

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#44]
http://www.gldesert.com/forums/showthread.php?9366-Anti-Hack-plugin&p=57380#post57380

**Comment by Joannou1** [comment]
I gave a bunch more perms, don't have any clients to test it on though.. leme know.

**Comment by Kladdkaka** [comment]
I can try it in 1-2 hours mind adding /fly & the nocheat perms to Picidae so I can try?

**Comment by TyJcksn** [comment]
Seems to be good
