### ISSUE TITLE
Mineable spawners in 1.8 broken

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#45]
Just as the title says mineable spawners seems to have broken when we updated to 1.7.10

**Comment by Joannou1** [comment]
So, I updated it to the very latest version possible and mined it... Seems to work
![Spawner1](http://gld.bz/c/2c033.png)
![Spawner2](http://gld.bz/c/1d363.png)

Leme know otherwise

**Comment by TyJcksn** [comment]
Awesome
