### ISSUE TITLE
Lightroll trails

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#46]
People who win a trail from Lightroll are unable to access any of the trails. No /trail perms

**Comment by Joannou1** [comment]
So the unfortunate thing with trails is... it shows you all the trails no matter what perms you have, and you have to guess which ones you have access too it seems..

So that makes giving the special one very difficult.. I will look into this a bit more.

**Comment by TyJcksn** [comment]
It makes it all the more special when you find out which one you have lol
