### ISSUE TITLE
Extream lag

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#48]
All the GLS' have been dying from lag since the 1.8 update? Is there a way to fix this? It's pretty bad.

**Comment by Joannou1** [comment]
Not sure what the cause of this is...
Have only seen one or two spikes here or there.
Some TPS lag from iron golems it seems.. Console is schedules to run a killall all every 15 minutes..
So maybe that will help.

**Comment by InMyToboggan** [comment]
It seems Iron golems aren't being killed in grinders, Dapoopey showed me his, and there were tonnes sitting in there, not dying, although the setup was the same as it has always been.

**Comment by TyJcksn** [comment]
That's a 1.8 thing, you have to kill them by hand now @inmytoboggan . Blame mojang
