### ISSUE TITLE
Bounty Plugin (from old repo)

### ISSUE THREAD

**Issue by Kladdkaka** [Joannou1/GLServers#5]
TJ1632 commented 2 days ago
A hardcore pvp server like GLD should have an Bounty Plugin. This will open a broad range of new things for players to participate in. Honestly being a bounty hunter on GLD would be pretty bad ass.
http://dev.bukkit.org/bukkit-plugins/bounty-snorri/
Xenu99

Xenu99 commented 21 minutes ago
this costs, but looks amazing http://www.spigotmc.org/resources/premiumbounty-gui-included.870/

**Comment by Joannou1** [comment]
I installed the bounty plugin called "HeroBounty".
Set up all the cost percentages and perms... Works really well.
I would like to buy that gui one, it looks great.. Lets see how the regular bounty one works first though.
