### ISSUE TITLE
1.8 Broke Anvils

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#50]
As the title says, only people in creative can use them.

**Comment by Joannou1** [comment]
I got GLDev on the case and was able to repair a diamond pick with another.
Are you sure about this?

**Comment by TyJcksn** [comment]
I've been having to repair other peoples tools so unless they're missing some form of a perm that I have

**Comment by TyJcksn** [comment]
Still seems to be an issue

**Comment by TyJcksn** [comment]
Seems like it's the 1.8 plugin. Gonna have to wait till they fix it.
