### ISSUE TITLE
Bungee related issues / suggestions

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#51]
The players are using /glist showall to find out which hidden staff are on, we may want to remove this perm from them.

**Comment by TyJcksn** [comment]
Implement a global chat for all the servers, players will love being able to talk to each other while they are playing different games. (Some commands will need to be disabled so that we can let other plugins take over on certain commands, such as our ban management plugin will need priority over this plugins ban option) 

http://www.spigotmc.org/resources/cloudchat.266/

**Comment by Kladdkaka** [comment]
We already got a bungee chat plugin, we only need to make a new channel
