### ISSUE TITLE
Lightroll points

### ISSUE THREAD

**Issue by InMyToboggan** [Joannou1/GLServers#53]
Now that's it's on the website that each rank gets so many rolls, like risen titan with 30, won't people who are already risen what these rolls? What should we tell them?

**Comment by Joannou1** [comment]
To upgrade ranks, or donate for something.. I already gave a different numbers of rolls to the ranks just to be friendly and encourage donations

**Comment by TyJcksn** [comment]
They're not getting 30 rolls @inmytoboggan

**Comment by InMyToboggan** [comment]
Ok, thanks Joan, and that's what I assumed TJ. But like the other thing's, if you went from default to Risen Titan, they the person would get 30 right?

**Comment by TyJcksn** [comment]
Correct
