### ISSUE TITLE
XP Bank Plugin - Plugin Changes (from old repo)

### ISSUE THREAD

**Issue by Kladdkaka** [Joannou1/GLServers#6]
TJ1632 commented 3 days ago
GLD could use another XP Bank plugin.
This plugin allows you to store xp in bottles, making it so it can be sold later on; and awesome perk for a pvp server like GLD. It also allows the usage of signs!

http://dev.bukkit.org/bukkit-plugins/xp-jar/

It says that it's last update was in 1.6.4 but the dev mentions that it still works for 1.7

Xenu99 commented 32 minutes ago
this could be used http://dev.bukkit.org/bukkit-plugins/xpshop/

**Comment by Joannou1** [comment]
Added the XP bank, configured configs + perms and tested.

I like it, good feature.

Be sure to let people know of its existence.

**Comment by Joannou1** [comment]
Also, do you think this should remain a general perk?
No rank, etc.

**Comment by TyJcksn** [comment]
I think it should be a donor perk like it was on old Gld, maybe give it to DL+ Or 1337+ ?
