### ISSUE TITLE
Vanish and possible staff abuse

### ISSUE THREAD

**Issue by Kindofjakii** [Joannou1/GLServers#62]
Current vanish doesn't allow staff members to see other staff members in vanish (as their player bodies), could be an easy way to abuse and it'd be hard to catch them, might want to have a look into why it's not giving other staff visibility to vanished players.

**Comment by TyJcksn** [comment]
Not really a big issue.

**Comment by Kindofjakii** [comment]
yea, bigger issues, just pointing it out if there's an easy fix

**Comment by TyJcksn** [comment]
Not pressing
