### ISSUE TITLE
Update the thread

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#67]
http://www.minecraftforum.net/forums/servers/pc-servers/survival-servers/743370-1-7-5-great-light-desert-desert-war-pvp-towny#c46

Add the new information, such as the recent server additions, hub addition, new plugins, that we're 1.8, etc.

**Comment by Kladdkaka** [comment]
Minecraftforums removes threads for servers that doesn't comply with the
EULA
Den 5 dec 2014 04:36 skrev "TJ1632" notifications@github.com:
