### ISSUE TITLE
Builder server

### ISSUE THREAD

**Issue by Kladdkaka** [Joannou1/GLServers#8]
A server with worldedit and voxelsniper for the buildteam

**Comment by MystHawk** [comment]
yes pls

**Comment by Joannou1** [comment]
Will get this done asap.

**Comment by Kladdkaka** [comment]
Awesome thanks!

**Comment by Joannou1** [comment]
Alright, the stuff has been set up on the Dev server.

IP: dev.gld.bz

WorldEdit given to Default group, whitelist is on.
Leme know who should be whitelisted exactly.

Also, /warp build once you are on, in case you don't spawn there already.
It's a big flatland area.
